theme: jekyll-theme-minimal
site: 
  logo: /portrait.jpg
  title: Zitai Chen | SYSU
  keywords: Homepage, CV, Academic, Tensor Method
  description: Homepage of Zitai Chen


author: Zitai Chen
avatar: /portrait.jpg

