theme: jekyll-theme-minimal
title: Zitai Chen | SYSU
logo: /portrait.jpg

keywords: Homepage, CV, Academic, Tensor Method
description: Homepage of Zitai Chen


author: Zitai Chen
avatar: /portrait.jpg

